return {
  {
    "stevearc/conform.nvim",
    event = { "BufReadPre", "BufNewFile" },
    opts = {
      formatters_by_ft = {
        javascript = { "prettier" },
        javascriptreact = { "prettier" },
        typescript = { "prettier" },
        typescriptreact = { "prettier" },
        css = { "prettier" },
        html = { "prettier" },
        json = { "prettier" },
        jsonc = { "prettier" },
        yaml = { "prettier" },
        markdown = { "prettier" },
        ["markdown.mdx"] = { "prettier" },
        graphql = { "prettier" },
        handlebars = { "prettier" },
        lua = { "stylua" },
      },
    },
    -- opts = {
    --   formatters_by_ft = {
    --     ["astro"] = { "prettier" },
    --     ["javascript"] = { "prettier" },
    --     ["javascriptreact"] = { "prettier" },
    --     ["typescript"] = { "prettier" },
    --     ["typescriptreact"] = { "prettier" },
    --     ["vue"] = { "prettier" },
    --     ["css"] = { "prettier" },
    --     ["scss"] = { "prettier" },
    --     ["less"] = { "prettier" },
    --     ["html"] = { "prettier" },
    --     ["json"] = { "prettier" },
    --     ["jsonc"] = { "prettier" },
    --     ["yaml"] = { "prettier" },
    --     ["markdown"] = { "prettier" },
    --     ["markdown.mdx"] = { "prettier" },
    --     ["graphql"] = { "prettier" },
    --     ["handlebars"] = { "prettier" },
    --     ["sql"] = { "sql_formatter" },
    --   },
    -- },
  },
}
